### ISSUE TITLE
Add Background music

### ISSUE THREAD

**Issue by MarkusKrug** [mofr/Diablerie#3]

**Comment by mofr** [comment]
Sound streaming should be implemented in order to complete music playback. It would be great to respect level sound theme settings. Also Sounds.txt Block1,2,3 columns are also related to the music looping.

**Comment by mofr** [comment]
Description of SoundEnviron.txt http://d2mods.info/forum/viewtopic.php?f=6&t=58717&view=next
It has `Song` column which is a reference to the background music track from Sounds.txt.

**Comment by mofr** [comment]
Background music and environment ambient sounds are implemented.
