### ISSUE TITLE
README does not include any compiling and running instructions

### ISSUE THREAD

**Issue by psycho23** [mofr/Diablerie#32]
I can easily get this package for my Linux Mint 17.3 to start compiling C# files:
mono-mcs - Mono C# 2.0 / 3.0 / 4.0 / 5.0  compiler for CLI 2.0 / 4.0 / 4.5

**Comment by mofr** [comment]
There is no prebuilt package at the moment. You need to have Unity 5.6.0f3 and diablo mpq files in order to run the game.

Thanks, for the issue report, I'll add the instructions to README file soon.

**Comment by psycho23** [comment]
Oh yeah I got all 6 mpq files :)

I need to go to bed right now so I can't Google. But you can make this faster for me when I get up, what's the best way to get Unity 5.6.0f3 for Linux to compile or use to compile C# files? What version of C# are you guys compiling to (I'm 90% sure I can find out by checking the source code of Diablerie within 8 minutes but like I said I'm going to bed and I want to save 3 minutes when I wake up lol)? CLI 4.5? or CLI 5+?

**Comment by mofr** [comment]
Unity supports a subset of the .NET Framework features up to about 3.5, and it runs a CLR 2.0.

Regarding Unity editor installation, try this: https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

By the way, I think that source code will require some minor changes, mainly due to file paths case sensitivity, because I'm working on a windows machine.

**Comment by mofr** [comment]
psycho23, do you have any updates on the topic? Did you tried to install linux version of Unity editor?

**Comment by psycho23** [comment]
I'm getting the Unity Editor .deb right now.
Found here:
https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/#post-3070212
to here:
http://beta.unity3d.com/download/6a86e542cf5c/public_download.html
It will be downloaded in 26 minutes.
It is 2.5GB. I have a feeling the Unity Editor is only gonna use like 10% of the files' it uses file-space, which is only 250 MB.
I'm 14% sure I will have Diablerie mirrored and running and the results reported here within 3 hours.

**Comment by psycho23** [comment]
Alright. I'm no longer gonna try and test run Diablerie because I'm not installing Unity Editor.

**Comment by mofr** [comment]
@psycho23, sorry, I didn't get why Unity Editor installation has failed. 
Anyway, I'm going to setup automated build and it will simplify the process (#36). It will happen once Unity 2017.1 is released.

**Comment by psycho23** [comment]
The Unity Editor installation is did not fail.
I am not going to install the Unity Editor because I detect there is a 0.4% chance it has malicious capabilities. Firefox is 17% malicious and/or 100% potentially malicious and yet I use it everyday. I guess Diablerie is just not that important to me. I am sorry.

**Comment by mofr** [comment]
Thanks for the explanation. By the way, how do you calculate those chances?

**Comment by psycho23** [comment]
I do not know. But I will tell you the facts along with some questions (all of these commands are done in bash on a Linux Mint 17.3):

`du -b unity-editor_amd64-5.6.1xf1Linux.deb`
2642299160	unity-editor_amd64-5.6.1xf1Linux.deb
`du -h unity-editor_amd64-5.6.1xf1Linux.deb`
2.5G	unity-editor_amd64-5.6.1xf1Linux.deb

$ sudo apt-get install -y atools > /dev/null 2>&1 #for displaying any compressed (deb, zip, .tgz, .tar.bz2) files -- and I also use this to unpack intelligently (always into one directory) and pack easily into zip or .tar.gz or .tar.bz2 with one simple 2 command-line option stroke with `apack`
$ als unity-editor_amd64-5.6.1xf1Linux.deb > unity-editor-als-out.txt

`egrep -v '/$' unity-editor-als-out.txt | wc -l`
11300

$ echo $((\`egrep '/$' unity-editor-als-out.txt | wc -l\` - 1))
2156

$ less unity-editor-als-out.txt #observing and saw:
"opt/Unity/Editor/Data/UnityExtensions/Unity/VR"
How many people use this extension that comes with this package that everyone must install by default?
"opt/Unity/Editor/Data/PlaybackEngines/MacStandaloneSupport/Variations/macosx32_nondevelopment_mono/UnityPlayer.app/Contents/Data/Managed/etc/mono/2.0/Browsers/Compat.browser"
Why is there a path this big in this package?


`echo "Doing regex search on the paths of the files/directories in the 5.6.1 Unity Editor ?beta? deb package for debian-based linuxes:"; for i in nodejs '\.bat$' '\.dll$' '\.exe$' '\.jar$'; do echo -n "Line-by-line regex: /$i/   "; egrep "$i" unity-editor-als-out.txt | wc -l | tr '\n' ' '; echo ' lines.'; done`
Doing regex search on the paths of the files/directories in the 5.6.1 Unity Editor ?beta? deb package for debian-based linuxes:
Line-by-line regex: /nodejs/   2356  lines.
Line-by-line regex: /\.bat$/   60  lines.
Line-by-line regex: /\.dll$/   1477  lines.
Line-by-line regex: /\.exe$/   133  lines.
Line-by-line regex: /\.jar$/   170  lines.

Why do they need nodejs?
Why is there 2356 entries of nodejs in my `als unity-editor_amd64-5.6.1xf1Linux.deb` output?
So Unity uses mono and that's why there are so many DLL files and EXE files?
Why is Unity using JAR files? (personal: Unity uses both the JRE and mono runtime?)
Why are there 1477 DLL files?

**Comment by psycho23** [comment]
The 13457-lined unity-editor-als-out.txt
https://gist.github.com/psycho23/dc50c2d634b708a96e465c0e9da37a63

**Comment by mofr** [comment]
Unity Editor is able to build the game to all other platforms. For example, I can build linux version of Diablerie on my windows machine. So Unity does contain all platforms runtimes in order to be able to build the game to all of them. That is why linux version of Unity Editor has exe, dll, jar and other files. Don't forget that Unity Editor is a developer tool, not for the end-users.
P.S. Take a look at the supported platform list https://unity3d.com/unity/multiplatform

**Comment by mofr** [comment]
Running instructions were added to README file. It will become easier once #36 is done.
