### ISSUE TITLE
Add a main menu to the game

### ISSUE THREAD

**Issue by MarkusKrug** [mofr/Diablerie#5]

**Comment by mofr** [comment]
Main features
* new game and character selection screen
* load game (game save is not impleneted yet however)
* quit game

So basically the main task is to implement character creation screen. Also I think it should be a separate scene than in-game process, so the game should be adapted to scene transitions.

**Comment by mofr** [comment]
Main menu Diablo fire animation:
data\global\ui\FrontEnd\D2logoFireLeft.DC6
data\global\ui\FrontEnd\D2logoFireRight.DC6

**Comment by mofr** [comment]
Also add scene transition visualization, at least static image.
