### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by mofr** [mofr/Diablerie#82]
Currently, the game freezes during resource loading. The task is to make it more comfortable for the user by adding a loading screen to show the loading progress.
- [x] Eager load on main menu enter (mpq, txt, animdata, palettes)
- [x] Consider using Unity job system to offload from the main thread and benefit from multiple cores
- [x] Show loading screen during act loading/switching
![image](https://user-images.githubusercontent.com/1718475/69556418-3d5b4b80-0fd7-11ea-9e61-030dd9cc8318.png)

**Comment by mofr** [comment]
Unity job system is designed to work within a single frame, so it's not appropriate.

**Comment by KillahNeo** [comment]
Let me help you to enhance the game's textures / images ?

![2323](https://user-images.githubusercontent.com/47231209/70203289-231e1d80-16fb-11ea-9cec-4f6960252bc8.jpg)

**Comment by mofr** [comment]
@KillahNeo Looks nice! How did you do it?

**Comment by mofr** [comment]
Regarding your question, it would be really nice. However, I can't include it into the project as is because it's basically Blizzard resource and it's not legal to distribute it.
It's possible to make a patch MPQ to override the original resources with higher-dimensional like this one.

**Comment by KillahNeo** [comment]
Oh i'd love to do that, i tweaked the image with photoshop cs2019
Anyways, if you tell me how to do it i can start working on it

**Comment by mofr** [comment]
Image path: `data\global\ui\Loading\loadingscreen.dc6`
