### ISSUE TITLE
Linux Build for Share

### ISSUE THREAD

**Issue by liberodark** [mofr/Diablerie#83]
That is a last build of Diablerie https://my.pcloud.com/publink/show?code=kZFUoYkZMLFgbUHfqxL3EwAsgcmvtVonw43y

If you want to share.

Best Regards

**Comment by mofr** [comment]
Thanks! I'll keep it here because I have an automated system to publish builds from Unity Cloud Build, so it's easier to wait a bit for the latest version support.

**Comment by mofr** [comment]
Linux version is built by Unity cloud Build now.
