### ISSUE TITLE
Missing Shadow Layer

### ISSUE THREAD

**Issue by giviz** [mofr/Diablerie#89]
It seems you forgot to build the shadow layer, it's use in the Rogue camp for example for the shadow on the fences.

[LevelBuilder](https://github.com/mofr/Diablerie/blob/c2ea2c86518ff2597bb6445941b5884644352547/Assets/Scripts/Diablerie/Engine/World/LevelBuilder.cs#L205)

**Comment by giviz** [comment]
Just to add up, the shadow layer is all tiles with orientation 13.

![Screenshot 2020-01-19 at 10 41 57 AM](https://user-images.githubusercontent.com/3670552/72682209-6cf37500-3aa9-11ea-8882-e92d8b8dcd5c.png)

Loading the shadows after the floor and using the floor layer works fine :)

**Comment by mofr** [comment]
![image](https://user-images.githubusercontent.com/1718475/72684571-49b1df80-3b14-11ea-9694-c53ed100ab3b.png)
