### ISSUE TITLE
How to use EditorTools ?

### ISSUE THREAD

**Issue by giviz** [mofr/Diablerie#94]
Can you explain the steps required in order to use EditorTools.cs ?

It seems that it's supposed to add a menu on the editor (which doesn't seems to be the case ?) and would allow to convert the original files into png ? How do you run it ?

I'm also not sure what the Selection.activeObject referrer to ? As all datas are into MPQ archives, how do you select a specific DT1 for example ?

Thanks !

**Comment by mofr** [comment]
EditorTools add context menu items. Selection represents Unity editor files selection. So to use it you have put dt1/dc6/etc files to Assets folder.
These tools do not work with MPQ files.
Please let me know if you need more clarifications.

**Comment by giviz** [comment]
Awesome, I managed to get it working on a windows VM :) Doesnt work on mac os because of the MPQ required to get the Palette and doesn't seems to work on linux either (context menu not added).

Thanks !
